export type Module =
  | "Init"
  | "Localization"
  | "Spaciiing"
  | "Shortcut"
  | "Framer"
  | "LoremGenerator"
  | "Instantiater"
  | "Renamer"
  | "VariableEditor"
  | "VirtualProfile"
  | "SelectionFilter"
  | "PluginSetting"
  | "LicenseManagement"
  | "AspectRatioHelper"
  | "Resize"
  | "StyleIntroducer"
  | "PropertyClipboard";
