export { default as LoremIpsumModal } from "./LoremIpsumModal";
export { default as FindAndReplaceModal } from "./FindAndReplaceModal";
export { default as IconTemplateModal } from "./IconTemplateModal";
export { default as FramerModal } from "./FramerModal";
export { default as MagicObjectModal } from "./MagicObjectModal";
export { default as UnifyTextModal } from "./UnifyTextModal";
export { default as ActivateLicenseModal } from "./ActivateLicenseModal";
export { default as CatalogueSettingModal } from "./CatalogueSettingModal";
export { default as FreeUserDelayModal } from "./FreeUserDelayModal";
export { default as StrokeEditModal } from "./StrokeEditModal"
export { default as NumberingModal } from "./NumberingModal";
export { default as SpiltTextModal } from "./SpiltTextModal"
export { default as CreateSectionModal } from "./CreateSectionModal";